### PR TITLE
autosave: init

### PR DESCRIPTION
**Pull request by MikaelFangel**
Add the auto save feature, which is loaded by default and triggers on leaving insert mode.

### CODE REVIEW

**Review by Greve2001 — COMMENTED** [review]
Nice! :unicorn:

**Comment by MikaelFangel** [comment]
@Greve2001 Is this an approval? 😅

**Comment by Greve2001** [comment]
I fucked up!

**Comment by Greve2001** [comment]
Please re request. Jeg kan ikke approve nu😂

**Pull request merged**
